management:
  security:
    enabled: false
server:
  port: 8801
spring:
  application:
    name: server1
  zipkin:
    base-url: http://192.168.5.48:9411/
    enabled: true
  sleuth:
    sampler:
      percentage: 1
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://192.168.5.49:8765/eureka
logging:
  level:
    root: info
server2.ribbon.NFLoadBalancerRuleClassName: com.netflix.loadbalancer.BestAvailableRule
#com.sun.management.jmxremote.port: 1098
#com.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=8999
#com.sun.management.jmxremote.ssl: false
#com.sun.management.jmxremote.authenticate: false
#endpoints:
#  actuator:
#    enabled: true
