server:
  port: 8804
spring:
  application:
    name: server4
  zipkin:
      base-url: http://192.168.5.48:9411/
      enabled: true
  sleuth:
    sampler:
      percentage: 1
eureka:
  client:
    service-url:
      defaultZone: http://192.168.5.49:8765/eureka
